# Завдання 3

## Задачі з Introduction to Data Science in Python

### Question 1

In [1]:
import numpy as np
import pandas as pd

In [2]:
def answer_one():
    
    url_Energy = './DATA/Energy Indicators.xls'
    energy = pd.read_excel(url_Energy, skiprows=17, skipfooter=38)
    energy.drop(columns=['Unnamed: 0', 'Unnamed: 1'], inplace=True)
    energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Country'] = energy['Country'].str.replace(r' \([\w\s]+\)', '', regex=True)
    energy['Country'] = energy['Country'].str.replace(r'\d+', '', regex=True)
    new_name_country = {
    'Republic of Korea': 'South Korea',
    'United States of America': 'United States',
    'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom',
    'China, Hong Kong Special Administrative Region': 'Hong Kong'
    }
    energy['Country'] = energy['Country'].replace(new_name_country)

    energy['Energy Supply'] = energy['Energy Supply'].apply(lambda x: x if isinstance(x, int) else np.nan)
    energy['Energy Supply'] = energy['Energy Supply'] * 1000000
    url_Gdp = './DATA/world_bank.csv'
    GDP = pd.read_csv(url_Gdp, skiprows=4)
    GDP['Country Name'] = GDP['Country Name'].replace({
        "Korea, Rep.": "South Korea",  
        "Iran, Islamic Rep.": "Iran", 
        "Hong Kong SAR, China": "Hong Kong"})
    GDP.rename(columns={'Country Name': 'Country'}, inplace=True)
    url_ScimEn = './DATA/scimagojr-3.xlsx'
    ScimEn = pd.read_excel(url_ScimEn)
    ScimEn = ScimEn.sort_values(by='Rank', ascending=True)
    ScimEn = ScimEn.iloc[:15]
    first = pd.merge(ScimEn, GDP, on='Country', how='inner')
    rez = pd.merge(first, energy, on='Country', how='inner')
    rez = rez[['Country', 'Rank', 'Documents', 'Citable documents', 
               'Citations', 'Self-citations', 'Citations per document', 
               'H index', 'Energy Supply', 'Energy Supply per Capita', 
               '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    rez.set_index('Country', inplace=True)
    return rez

In [3]:
answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

### Question 2

In [4]:
def answer_two():
    
    col = np.arange(10,20).tolist()
    dat = answer_one().columns[col]
    avgGDP = answer_one()[dat].mean(axis=1).sort_values(ascending=False)
    
    
    return avgGDP

In [5]:
answer_two()

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

### Question 3

In [6]:
def answer_three():
    
    q4 = answer_two()
    q4 = q4.sort_values(ascending=False)
    r_i = q4.index[5]
    return answer_one().loc[r_i, '2015'] - answer_one().loc[r_i, '2006']

In [7]:
answer_three()

246702696075.3999

### Question 4

In [8]:
def answer_four():
    
    q7 = answer_one()
    q7['ratio'] = q7['Self-citations'] / q7['Citations']
    return q7['ratio'].idxmax(), q7['ratio'].max()

In [9]:
answer_four()

('China', 0.6893126179389422)

### Question 5

In [10]:
def answer_five():
    
    q8 = answer_one()
    q8['pop'] = (q8['Energy Supply'] / q8['Energy Supply per Capita'])
    rez = q8['pop'].sort_values(ascending=False)
    return rez.index[2]

In [11]:
def answer_five():

    q9 = answer_one()
    q9['pop'] = (q9['Energy Supply'] / q9['Energy Supply per Capita'])
    q9['Citable documents pop'] = q9['Citable documents'] / q9['pop']
    q9 = q9[['Citable documents pop', 'Energy Supply per Capita']].astype('float64')
    return q9['Citable documents pop'].corr(q9['Energy Supply per Capita'])

In [12]:
answer_five()

0.7940010435442946

### Question 6

In [13]:
def answer_six():

    q9 = answer_one()
    q9['pop'] = (q9['Energy Supply'] / q9['Energy Supply per Capita'])
    q9['Citable documents pop'] = q9['Citable documents'] / q9['pop']
    q9 = q9[['Citable documents pop', 'Energy Supply per Capita']].astype('float64')
    return q9['Citable documents pop'].corr(q9['Energy Supply per Capita'])

In [14]:
answer_six()

0.7940010435442946

### Question 7

In [15]:
def answer_seven():
    ContinentDict = {
        'China': 'Asia',
        'United States': 'North America',
        'Japan': 'Asia',
        'United Kingdom': 'Europe',
        'Russian Federation': 'Europe',
        'Canada': 'North America',
        'Germany': 'Europe',
        'India': 'Asia',
        'France': 'Europe',
        'South Korea': 'Asia',
        'Italy': 'Europe',
        'Spain': 'Europe',
        'Iran': 'Asia',
        'Australia': 'Australia',
        'Brazil': 'South America'
    }

    Top15 = answer_one()
    Top15['pop'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Continent'] = Top15.index.map(ContinentDict)

    new_df = pd.DataFrame(index=['Asia', 'Australia', 'Europe', 'North America', 'South America'], columns=['size', 'sum', 'mean', 'std'])
    grouped = Top15.groupby('Continent')['pop']

    new_df['size'] = grouped.count()
    new_df['sum'] = grouped.sum()
    new_df['mean'] = grouped.mean()
    new_df['std'] = grouped.std()

    return new_df

In [16]:
answer_seven()

               size               sum              mean           std
Asia              5   2898666386.6106   579733277.32212  6.790979e+08
Australia         1   23316017.316017   23316017.316017           NaN
Europe            6  457929667.216372   76321611.202729  3.464767e+07
North America     2   352855249.48025  176427624.740125  1.996696e+08
South America     1  205915254.237288  205915254.237288           NaN